name: Test with Buck

on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04 # Not latest, because python3.6 is not available on latest
                          # https://github.com/actions/setup-python/issues/544
    steps:
    - uses: actions/checkout@v2
    - name: Perform tests
      id: test
      uses: SandakovMM/build-with-buck@v2
      with:
        command: test
        target: :libs.tests
